import torch
import numpy as np
import models
import random
from time import time
import pandas as pd
import argparse
from scipy.fft import fft, ifft
from scipy.stats import levy_stable, norm

# The code used to generate ARFIMA process is sourced from the following GitHub repository: https://github.com/akononovicius/arfima/

def __ma_model(
    params: list[float],
    n_points: int,
    *,
    noise_std: float = 1,
    noise_alpha: float = 2,
) -> list[float]:
    """Generate discrete series using MA process.

    Args:
        params: list[float]
            Coefficients used by the MA process:
                x[t] = epsi[t] + params[1]*epsi[t-1] + params[2]*epsi[t-2] + ...
            Order of the MA process is inferred from the length of this array.
        n_points: int
            Number of points to generate.
        noise_std: float, optional
            Scale of the generated noise (default: 1).
        noise_alpha: float, optional
            Parameter of the alpha-stable distribution (default: 2). Default
            value corresponds to Gaussian distribution.

    Returns:
        Discrete series (array of length n_points) generated by
        MA(len(params)) process
    """
    ma_order = len(params)
    if noise_alpha == 2:
        noise = norm.rvs(scale=noise_std, size=(n_points + ma_order))
    else:
        noise = levy_stable.rvs(
            noise_alpha, 0, scale=noise_std, size=(n_points + ma_order)
        )

    if ma_order == 0:
        return noise
    ma_coeffs = np.append([1], params)
    ma_series = np.zeros(n_points)
    for idx in range(ma_order, n_points + ma_order):
        take_idx = np.arange(idx, idx - ma_order - 1, -1).astype(int)
        ma_series[idx - ma_order] = np.dot(ma_coeffs, noise[take_idx])
    return ma_series[ma_order:]

def __arma_model(params: list[float], noise: list[float]) -> list[float]:
    """Generate discrete series using ARMA process.

    Args:
        params: list[float]
            Coefficients used by the AR process:
                x[t] = params[1]*x[t-1] + params[2]*x[t-2] + ... + epsi[t]
            Order of the AR process is inferred from the length of this array.
        noise: list[float]
            Values of the noise for each step. Length of the output array is
            automatically inferred from the length of this array. Note that
            noise needs not to be standard Gaussian noise (MA(0) process). It
            may be also generated by a higher order MA process.

    Returns:
        Discrete series (array of the same length as noise array) generated by
        the ARMA(len(params), ?) process.
    """
    ar_order = len(params)
    if ar_order == 0:
        return noise
    n_points = len(noise)
    arma_series = np.zeros(n_points + ar_order)
    for idx in np.arange(ar_order, len(arma_series)):
        take_idx = np.arange(idx - 1, idx - ar_order - 1, -1).astype(int)
        arma_series[idx] = np.dot(params, arma_series[take_idx]) + noise[idx - ar_order]
    return arma_series[ar_order:]

def __frac_diff(x: list[float], d: float) -> list[float]:
    """Fast fractional difference algorithm (by Jensen & Nielsen (2014)).

    Args:
        x: list[float]
            Array of values to be differentiated.
        d: float
            Order of the differentiation. Recommend to use -0.5 < d < 0.5, but
            should work for almost any reasonable d.

    Returns:
        Fractionally differentiated series.
    """

    def next_pow2(n):
        # we assume that the input will always be n > 1,
        # so this brief calculation should be fine
        return (n - 1).bit_length()

    n_points = len(x)
    fft_len = 2 ** next_pow2(2 * n_points - 1)
    prod_ids = np.arange(1, n_points)
    frac_diff_coefs = np.append([1], np.cumprod((prod_ids - d - 1) / prod_ids))
    dx = ifft(fft(x, fft_len) * fft(frac_diff_coefs, fft_len))
    return np.real(dx[0:n_points])

def arfima(
    ar_params: list[float],
    d: float,
    ma_params: list[float],
    n_points: int,
    *,
    noise_std: float = 1,
    noise_alpha: float = 2,
    warmup: int = 0,
) -> list[float]:
    """Generate series from ARFIMA process.

    Args:
        ar_params: list[float]
            Coefficients to be used by the AR process.
        d: float
            Differentiation order used by the ARFIMA process.
        ma_params: list[float]
            Coefficients to be used by the MA process.
        n_points: int
            Number of points to generate.
        noise_std: float, optional
            Scale of the generated noise (default: 1).
        noise_alpha: float, optional
            Parameter of the alpha-stable distribution (default: 2). Default
            value corresponds to Gaussian distribution.
        warmup: int, optional
            Number of points to generate as a warmup for the model
            (default: 0).

    Returns:
        Discrete series (array of length n_points) generated by the
        ARFIMA(len(ar_params), d, len(ma_params)) process.
    """
    ma_series = __ma_model(
        ma_params, n_points + warmup, noise_std=noise_std, noise_alpha=noise_alpha
    )
    frac_ma = __frac_diff(ma_series, -d)
    series = __arma_model(ar_params, frac_ma)
    return series[-n_points:]

def simulation(d:float, T:int, ar:list, ma:list):
    replication = 500
    d_hat_list = []
    
    for r in range(replication):
        # set the seed
        torch.manual_seed(r)
        np.random.seed(r)
        random.seed(r)
        
        random_number = np.random.uniform(-1, 1, 1)[0]
        init_mem = [d - 0.05 * random_number]
        
        # gerenate the time series
        series = arfima(ar, d, ma, T, warmup=T)
        series = 2 * (series - np.min(series)) / (np.max(series) - np.min(series)) - 1
        X = torch.from_numpy(series[:-1].reshape(1, -1, 1)).float()
        Y = torch.from_numpy(series[1:].reshape(1, -1, 1)).float()
        train_X = X[:, :int(0.8 * T), :]
        train_Y = Y[:, :int(0.8 * T), :]
        val_X = X[:, int(0.8 * T):, :]
        val_Y = Y[:, int(0.8 * T):, :]
        # training 
        model = models.MRNNFModel('MGRUF', 1, 1, 1, 100, 'cpu', 0, init_mem)
        criterion = torch.nn.MSELoss()
        optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
        start_time = time()
        stuck = 0
        min_val_loss = np.inf
        for epoch in range(500):
            model.train()
            optimizer.zero_grad()
            output, _ = model(train_X)
            loss = criterion(output, train_Y)
            loss.backward()
            optimizer.step()
            
            model.eval()
            output, _ = model(val_X)
            val_loss = criterion(output, val_Y)
            if val_loss < min_val_loss:
                min_val_loss = val_loss
                stuck = 0
                # d_hat of the best model
                d_hat = 0.5 * torch.nn.functional.sigmoid(model.mem_para.detach())
            else:
                stuck += 1
            if stuck > 50:
                break
        print(f'replication = {r}, init_d = {init_mem[0]:.3f}, d_hat = {d_hat.numpy()[0]:.3f}, time = {(time() - start_time):.1f}')
        d_hat_list.append(d_hat.numpy())
    print(f'd = {d}, T = {T}, AR = {ar}, MA = {ma}, d_hat_mean = {np.mean(d_hat_list)}, std_d_hat = {np.std(d_hat_list)}')
    d_df = pd.DataFrame()
    d_df[f'd={d}'] = d_hat_list
    d_df.to_csv(f'results/simulation/T_{T}_ar_{ar[0]}_ma_{ma[0]}_d_{d}.csv')
    
    return d_hat_list

if __name__ == '__main__':
    for d in [0.1, 0.2, 0.3, 0.4]:
        for T in [500, 1000, 2000]:
            simulation(d, T, [0], [0])
            simulation(d, T, [0.2], [0.2])